name: Periodically Rotate Google Maps API Key
run-name: ${{ github.actor }} is rotating Google Maps API key 🚀
on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  rotate-api-key:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.2"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Try rotate the API key
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CREDENTIALS: ${{ secrets.ARM_CREDENTIALS }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          cd terraform && ./rotate-secret.sh
